appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
matrix:
- - [BLAS_VARIANT, openblas]
- - [BLAS_VARIANT, noblas]
- - [BLAS_VARIANT, mkl]
max_py_ver: '37'
max_r_ver: '35'
shippable:
  projectId: 5c338155d1578b070030d551
  secure: {BINSTAR_TOKEN: bkTdATvev7sVFsP62xFV2ck215nXEtH7eWXdhzRRtbzeKquSkNhTGTCoa5FcLDvAVe36w+Sv59/3/oWNyMood8pIWjHLMC5CqqLdc4NRmyyaCKWys4CLhTTurIBPFSWUilxZW1KCKv/WHOe+zQDi2o9R9lf5/MizuwThHSQOIcqeTIn4wtPzbne5MeKSW+mRCsb+l4E/Q1oY2w/mTJ+izDWkxefstZ2t8RqOxH6H20wwNOOj/1WdeztdCOtCAl99r8Aj58odGyfUMAEyw89c5HglAEPurBQs21DZbHp10NmgSLyIbukplulRUm+cQ37loT/hFfTjPUCqLEC3lu6SPw==}
travis:
  secure: {BINSTAR_TOKEN: BEN1r6lPEq1tY3QhVyDy1MPX94hcOeULeC9GlDKXUmASPW7ivzjll5PiXnCz3DxrZnjuI57u3HmPCU8/9pWRIV4c8z4d3NxBf95fkJE26Hc1+4MLeye7TNlST8hBxIhM4A8nbnJaVNScKaYnkozXFGrKqTD0NqWN4MP2SbbYGZo5lA8WczTQI0LDqYs1CfgpwEXamENAvzm5WTwMbiK4cVuXyGtQh5lbSbMCDSxl9OxhrFJLu4Lg3LHRmcQ84JNV2Rx1UubWkJ9ZclRjHRnbHwjc5gYH7q/8Ft3kEYNNwnamHN8GwTjTh7DTmhe1mAu1/2jidzyFZjv8wmxWDHFjBavQDAqHLWrbsxt/JNDnovEsVUR/JIj8Gwt+kHFHHYkqfSTwbLu6Hq6BKcPJ3e3/NwM905+4/xXrNO5p9iRESPYasKlFgFRrtUJCBZ/6UtpzKoRiB7CHFMSuV+b39ez3kwn/D9FEm0bbUe7Wod6HMnscQmf1m12LtNjhkYa9NfTuxLlM0r3Sgs+B2z1mvw8Fw4paWSrLN0Lnk/IzsuSfyIxw3RynNLgVtWWxV74kpBdXFzaqZndibf4VVfuax/I/PW4ygDiHv6pW5pVdLOu72rdHw05zyFOpS/FBpaZhux0gOs3UMFNGcyY2WdQny7MC/cA6ueaBR0OfoyLYStniNrQ=}
